### ISSUE TITLE
Gamedata is outdated

### ISSUE THREAD

**Issue by yumm-dev** [tsuza/tf2-knockback_modifier#2]
Plugin doesn't load at all due to the gamedata being out of date.

**Comment by tsuza** [comment]
Thanks. The gamedata should be correct now.

**Comment by yumm-dev** [comment]
There isn't any new release, or a codebase change. How can I get the new gamedata?

**Comment by tsuza** [comment]
Just replace the tf2.knockback_modifier.txt file found in gamedata with the following https://github.com/tsuza/tf2-knockback_modifier/blob/main/gamedata/tf2.knockback_modifier.txt 
Anyway thank you for reminding me, I'll soon push a new release.

**Comment by tsuza** [comment]
In case you haven't manually done it, it's under the 0.1.1 release now.
