### ISSUE TITLE
tf2.knockback_modifier.txt

### ISSUE THREAD

**Issue by PrettyViolet** [tsuza/tf2-knockback_modifier#4]
Hello! Could you please show me an example of how to fill in tf2.knockback_modifier.txt, so that for example I can put the kickback on Tomislav?

I'm just learning Attributes and honestly don't understand what, where and how.

**Comment by tsuza** [comment]
That's the gamedata of the plugin, which you should not touch. Take a look at: https://github.com/nosoop/SM-TFCustAttr/wiki/Applying-Custom-Attributes

**Comment by PrettyViolet** [comment]
> That's the gamedata of the plugin, which you should not touch. Take a look at: https://github.com/nosoop/SM-TFCustAttr/wiki/Applying-Custom-Attributes

Thank you very much for answering, but I still have nothing works, it is worth clarifying that I would like to change the attributes and model of existing weapons - at the moment did the following:

Installed all the necessary dependencies, put tf_custom_attributes.txt in configs. 
And also put the weapon model on the server and in the downloads folder of my tf2.
 (I wanted to use two of your plugins).

The contents of tf_custom_attributes.txt are as follows:

```
// Custom Attribute Manager sample file
// 
// This configuration file attaches custom attributes to weapons based on definition index.

"Custom Attributes"
{
	// Cloak and Dagger
	"13"
	{
		"cloak decrease"			"1"
	}
	
	// Rocket Launcher
	"18"
	{
		"set weapon model" "models/weapons/c_models/c_rocketlauncher/c_rocketlauncher.mdl"
                "knockback modifier" 	"3.0"
	}
	
	// Disciplinary Action
	"447"
	{
		"quack on crit check"		"1"
	}
	
	// Huo-Long Heater
	"811"
	{
		"minigun winddown boost duration"		"5.0"
	}
}
```

Also used the tf2custattrman_reload command, restarted the server and tf2 - but no model or recoil appeared. 
(I can assume that the recoil works only on weapons that originally had recoil, such as shotguns or grenade launchers).

But the lack of a model - definitely suggests that I missed something.

**Comment by tsuza** [comment]
Load / reload the plugin and see if it's complaining about something.

**Comment by PrettyViolet** [comment]
> Загрузите/перезагрузите плагин и посмотрите, жалуется ли он на что-нибудь.

sm plugins unload attribute_viewmodel_override
[SM] Plugin [TF2] Attribute: Viewmodel Override unloaded successfully.

sm plugins load attribute_viewmodel_override
[SM] Loaded plugin attribute_viewmodel_override.smx successfully.

sm plugins unload attr_knockback_modifier
[SM] Plugin [TF2-CA] Knockback Modifier unloaded successfully.

sm plugins load attr_knockback_modifier
[SM] Loaded plugin attr_knockback_modifier.smx successfully.

**Comment by PrettyViolet** [comment]
> Load / reload the plugin and see if it's complaining about something.

I also tried using debugger - this is what it says:
```
] sm_custattr_show
---- Attributes for entity 322 (tf_weapon_rocketlauncher)
set weapon model = 'models/weapons/c_models/c_rocketlauncher/c_rocketlauncher.mdl'
knockback modifier = '3.000000'
```

I also tried using other attributes - they don't work either, here's the logs:
```
] sm_custattr_add "health regen" "200.0"
Set attribute "health regen" to value "200.0" on active weapon.

] sm_custattr_show
---- Attributes for entity 322 (tf_weapon_rocketlauncher)
set weapon model = 'models/weapons/c_models/c_rocketlauncher/c_rocketlauncher.mdl'
knockback modifier = '3.000000'
health regen = '200.0'
```

**Comment by tsuza** [comment]
I know that it works fine both on the server I used to develop for and my testing server, so I don't think the plugin is the problem. Make sure that everything is working correctly, especially since, supposedly, other attributes aren't working as you've stated.

**Comment by PrettyViolet** [comment]
> I know that it works fine both on the server I used to develop for and my testing server, so I don't think the plugin is the problem. Make sure that everything is working correctly, especially since, supposedly, other attributes aren't working as you've stated.

Could you please send me the contents of your tf_custom_attributes.txt?

**Comment by tsuza** [comment]
I don't use that to set custom attributes. We use a custom plugin to give attributes to weapons, including custom attributes. You can probably find some online. Notnheavy should have one with custom attributes support iirc.

Nevertheless, the following should work:
```
"Custom Attributes"
{
	"424" // Tomislav
	{
		"knockback modifier"			"0.1"
	}
}
```
