### ISSUE TITLE
Off-topic question.

### ISSUE THREAD

**Issue by PrettyViolet** [tsuza/tf2-knockback_modifier#5]
Sorry for writing in issues, I do not know how to write to you in DM, 

I wanted to ask if it is possible to somehow change the sound of weapons in attributes plugin or is there any plugin with which it can be done?

**Comment by tsuza** [comment]
It's not *possible, since it's client-sided.

\* You can change it for others, but whoever is wielding the weapon will hear the original sound, on top of the custom one.

**Comment by PrettyViolet** [comment]
> Это *невозможно, так как это происходит на стороне клиента.
> 
> * Вы можете изменить его для других, но тот, кто владеет оружием, будет слышать оригинальный звук поверх пользовательского.

Thanks for the response!

I've seen in the custom weapon plugin settings a box that defines which sounds from the existing ones in the game will be played on this weapon.

Is it possible to do that with this plugin? https://github.com/NotnHeavy/TF2-Attribute-Manager

**Comment by tsuza** [comment]
If it's a custom attribute, sure. However, as I've mentioned, you can't really change weapon sounds nicely since it's client predicted.

**Comment by PrettyViolet** [comment]
> If it's a custom attribute, sure. However, as I've mentioned, you can't really change weapon sounds nicely since it's client predicted.

Thank you!
